apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yir7cm4mr-go 
  janus-idp.io/tekton: yir7cm4mr-go
  backstage.io/kubernetes-id: yir7cm4mr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yir7cm4mr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml