apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yir7cm4mr-go-gitops
  description: This is GitOps manifest for yir7cm4mr-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=yir7cm4mr-go
    backstage.io/kubernetes-id: yir7cm4mr-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: yir7cm4mr-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yir7cm4mr-go
